---
title: "README"
author: "Sergio Contente"
date: "`r Sys.Date()`"
output: github_document
bibliography: references.bib
---

# :sos: ROS Guide :robot:

# :memo: Introdução

A principal motivação de desenvolver este repositório é o fato de
poder documentar através de arquivos Markdown todo o conhecimento que
adquiri durante meus anos na equipe ThundeRatz de robótica da Escola
Politécnica da USP juntamente com o fato de poder injetar códigos em
diversas linguagens com instruções de execução local para que aqueles
que queiram ter o conhecimento acerda de Robot Operating System (ROS) o
faça de maneira interativa e ativa [@active-learning].

Além disso, todos os arquivos Markdown na verdade estão sendo gerados
a partir do RStudio usando R no formato Rmd com o uso de algumas
biblotecas que ajudam a facilitar a formatação geral do texto e a
geração das referências bibliográficas através de BibTeX.

# :open_file_folder: Estrutura dos Arquivos

- ROS-Guide: raíz do repositório
  - :seedling: ROS Basics: aborda questões relacionadas ao básico de
    ROS, perfeito para iniciantes.

# Bibliografia